import { Link } from "@/i18n/routing";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Home route</p>
        <div>
          <a href="/about">About us</a>
        </div>
        <div>
          <Link href="/" locale="en">
            Switch path to English
          </Link>
        </div>{" "}
        <div>
          <Link href="/" locale="de">
            Switch path to German
          </Link>
        </div>
      </main>
    </>
  );
}
